""" Block id codes here """
STARTING_BLOCK = 0
WOODEN_BLOCK = 1
MOTOR_WHEEL = 2
METAL_BLADE = 3
DECOUPLER = 4
HINGE = 5
SPIKE_BALL = 6
BRACE = 7
CONTRACTABLE_SPRING = 9
WOODEN_PANEL = 10
CANNON = 11
SCALING = 12
STEERING_BLOCK = 13
FLYING_BLOCK = 14
SMALL_WOODEN_BLOCK = 15
SUSPENSION = 16
CIRCULAR_SAW = 17
PISTON = 18
SWIVEL_JOINT = 19
METAL_SPIKE = 20
FLAME_THROWER = 21
SPINNING_BLOCK = 22
BOMB = 23
SMALL_METAL_PLATE = 24
WING = 25
AERODYNAMIC_PROPELLER = 26
GRABBER = 27
STEERING_HINGE = 28
CIRCULAR_METAL_PLATE = 29
HOLDER = 30
FLAMING_BALL = 31
RECTANGULAR_METAL_PLATE = 32
PLOW = 33
WING_PANEL = 34
BALLAST = 35
BOULDER = 36
HALF_PIPE = 37
UNPOWERED_MEDIUM_COG = 38
POWERED_MEDIUM_COG = 39
UNPOWERED_WHEEL = 40
WOODEN_POLE = 41
SLIDER = 42
BALLOON = 43
BALL_JOINT = 44
SIMPLE_ROPE_AND_WINCH = 45
LARGE_WHEEL = 46
SMALL_TORCH = 47
DRILL = 48
GRIP_PAD = 49
SMALL_WHEEL = 50
UNPOWERED_LARGE_COG = 51
SHRAPNEL_CANNON = 53
REMOTE_GRENADE = 54
SMALL_AERODYNAMIC_PROPELLER = 55
WATER_CANNON = 56
PIN_BLOCK = 57
CAMERA_BLOCK = 58
EXPLOSIVE_ROCKET = 59
UNPOWERED_LARGE_WHEEL = 60
REPEATING_CROSSBOW = 61
VACUUM = 62
LOG = 63

block_name = {
    0: 'STARTING BLOCK',
    1: 'WOODEN BLOCK',
    2: 'MOTOR WHEEL',
    3: 'METAL BLADE',
    4: 'DECOUPLER',
    5: 'HINGE',
    6: 'SPIKE BALL',
    7: 'BRACE',
    9: 'CONTRACTABLE SPRING',
    10: 'WOODEN PANEL',
    11: 'CANNON',
    12: 'SCALING',
    13: 'STEERING (BLOCK)',
    14: 'FLYING BLOCK',
    15: 'SMALL WOODEN BLOCK',
    16: 'SUSPENSION',
    17: 'CIRCULAR SAW',
    18: 'PISTON',
    19: 'SWIVEL JOINT',
    20: 'METAL SPIKE',
    21: 'FLAME THROWER',
    22: 'SPINNING BLOCK',
    23: 'BOMB',
    24: 'SMALL (SQUARE) METAL PLATE',
    25: 'WING',
    26: 'AERODYNAMIC PROPELLER',
    27: 'GRABBER',
    28: 'STEERING HINGE',
    29: 'CIRCULAR METAL PLATE',
    30: 'HOLDER',
    31: 'FLAMING BALL',
    32: 'RECTANGULAR METAL PLATE',
    33: 'PLOW',
    34: 'WNIG PANEL',
    35: 'BALLAST',
    36: 'BOULDER',
    37: 'HALF PIPE',
    38: 'UNPOWERED MEDIUM COG',
    39: 'POWERED MEDIUM COG',
    40: 'UNPOWERED WHEEL',
    41: 'WOODEN POLE',
    42: 'SLIDER',
    43: 'BALLOON',
    44: 'BALL JOINT',
    45: 'SIMPLE ROPE + WINCH',
    46: 'LARGE WHEEL',
    47: 'SMALL TORCH',
    48: 'DRILL',
    49: 'GRIP PAD',
    50: 'SMALL WHEEL',
    51: 'UNPOWERED LARGE COG',
    53: 'SHRAPNEL CANNON',
    54: 'REMOTE GRENADE',
    55: 'SMALL AERODYNAMIC PROPELLER',
    56: 'WATER CANNON',
    57: 'PIN BLOCK',
    58: 'CAMERA BLOCK',
    59: 'EXPLOSIVE ROCKET',
    60: 'UNPOWERED LARGE WHEEL',
    61: 'REPEATING CROSSBOW',
    62: 'VACUUM',
    63: 'LOG'
}
